ups/config/routes.rb
Ups::Application.routes.draw do
  resources :events do
    member do
      delete 'vote/:user_vote_id' => "events#user_vote_destroy", :as => :delete_user_votes
      put 'vote' => "events#vote", :as => :vote
      get 'timeslot/new' => "events#new_timeslot", :as => :new_timeslot
      delete 'timeslot/:timeslot_id' => "events#destroy_timeslot", :as => :destroy_timeslot
      get 'finish' => "events#finish", :as => :finish
      put 'reopen' => "events#reopen", :as => :reopen
      put 'finish' => "events#finished", :as => :finished
    end
  end

  match "/calendar" => "events#calendar", :via => :get
  match "/calendar/absence/new" => "events#new_absence", :via => :get, :as => :new_absence
  match "/calendar/absence" => "events#create_absence", :via => :post, :as => :create_absence
  resources :users
  resources :links
  resource :user, :only => :show, :as => :current_user

  resources :file_uploads, :except => [ :new, :show ] do
    collection do
      get ':page_id/new', :action => :new, :as => :new_with_page
    end
  end

  match "/downloads/:id" => "file_uploads#show", :as => :download_file

  match "/session/login" => "session#login", :via => :get
  match "/session/start" => "session#start", :via => :get
  match "/session/complete" => "session#complete", :via => :get
  match "/session/logout" => "session#logout", :via => :get

  match "/blog/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_news, :via => :get
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_news, :via => :delete
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_news, :via => :put
  resources :news, :controller => :pages do
    get 'rss', :on => :collection
  end

  resources :categories, :except => :show

  match "/page/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_page, :via => :get
  match "/page/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_page, :via => :delete
  match "/page/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_page, :via => :put
  resources :pages do
    member do
      get 'activate'
      get 'deactivate'
    end
    collection do
      get 'preview'
      get ':id/:comment_id/edit', :action => :edit_comment, :as => :edit_comment
      put ':id/:comment_id', :action => :update_comment, :as => :update_comment
      post ':id/create_comment', :action => :create_comment, :as => :create_comment
      post ':id/create_comment_preview', :action => :create_comment_preview, :as => :create_comment_preview
      delete ':id/:comment_id/destroy_comment', :action => :destroy_comment, :as => :destroy_comment
    end
  end

  match "/config" => "conf#index", :via => :get
  match "/config" => "conf#update", :via => :put
  match "/config/check_twitter" => "conf#check_twitter", :via => :get
  match "/config/check_google" => "conf#check_google", :via => :get
  match "/config/create_google_calendar" => "conf#create_google_calendar", :via => :post
  match "/config/pull_github" => "conf#pull_github", :via => :get

  match "/credits" => "pages#credits"
  match "/setup" => "pages#setup"

  if Rails.env.development?
    match "/backdoor" => "users#backdoor", :via => :get
  end

  root :to => "pages#home"

#   match "*a" => "application#http_404"
end

ups/app/views/layouts/_categories.html.erb
<div class="list categories">
  <% if page.present? && page.categories.any? %>
  <h2>categories:</h2>
  <%= list_categories_for(page) %>
  <% end %>
</div>

ups/app/views/layouts/_languages.html.erb
<div class="list languages">
  <% if page.present? %>
  <h2>select language:</h2>
  <ul>
    <% languages.each do |language| %>
    <li>
      <%= link_to language.name, show_page_path(page.id, page.int_title, language.short) %>
    </li>
    <% end %>
  </ul>
  <% end %>
</div>

ups/app/views/layouts/_menu.html.erb
<ul>
  <% visible_children_pages(nil).each do |page| %>
  <li>
    <%= link_to page_title(page), make_page_path(page) %>
    <% children = visible_children_pages(page) %>
    <% if children.any? %>
    <ul>
      <% children.each do |child| %>
      <li>
        <%= link_to page_title(child), make_page_path(child) %>
      </li>
      <% end %>
    </ul>
    <% end %>
  </li>
  <% end %>
</ul>
<div class="clear">
</div>

ups/app/views/layouts/_tags.html.erb
<div class="list tags">
  <% if page.present? && page.tags.any? %>
  <h2>tags:</h2>
  <%= list_tags_for page %>
  <% end %>
</div>

ups/app/views/layouts/_user_menu.html.erb
<%= link_to_unless signed_in?, "login", session_login_path, :class => "login" do %>
      <%= link_to "profile", current_user_path, :class => "user" %>
      <%= link_to "logout", session_logout_path, :class => "logout" %>
<% end %>

ups/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= make_title %></title>
    <%= auto_discovery_link_tag :rss, :controller => :pages, :action => :rss %>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'jquery-ui-1.8.10.custom.min.js' %>
    <%= javascript_include_tag 'rails' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <header>
      <h1><%= link_to Conf.web_name, root_path %></h1>
      <nav class="actions"><%= render 'layouts/user_menu' %><%= link_to "credits", credits_path, :class => "credits" %></nav>
    </header>
    <nav id="menu">
      <%= render 'layouts/menu' %>
    </nav>
    <section id="content">
      <% if make_page_title.present? %>
      <h1><%= make_page_title %></h1>
      <% end %>
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
      <% end %>
      <%= yield %>
	  <div class="clear"></div>
    </section>
    <footer>
      <%= render 'layouts/categories', :page => @page %>
      <%= render 'layouts/tags', :page => @page %>
      <%= render 'layouts/languages', :page => @page, :languages => @languages %>
      <%= render 'shared/twitter' %>
      <%= render 'shared/linklist' %>
      <% if Rails.env.development? %>
      <%= render 'shared/backdoor', :user => @current_user if signed_in? %>
      <div class="list debug">
        <%= debug(params) %>
      </div>
      <% end %>
    </footer>
  </body>
</html>