ups/config/routes.rb
Ups::Application.routes.draw do
  resources :events do
    member do
      delete 'vote/:user_vote_id' => "events#user_vote_destroy", :as => :delete_user_votes
      put 'vote' => "events#vote", :as => :vote
      get 'timeslot/new' => "events#new_timeslot", :as => :new_timeslot
      delete 'timeslot/:timeslot_id' => "events#destroy_timeslot", :as => :destroy_timeslot
      get 'finish' => "events#finish", :as => :finish
      put 'reopen' => "events#reopen", :as => :reopen
      put 'finish' => "events#finished", :as => :finished
    end
  end

  match "/calendar" => "events#calendar", :via => :get
  match "/calendar/absence/new" => "events#new_absence", :via => :get, :as => :new_absence
  match "/calendar/absence" => "events#create_absence", :via => :post, :as => :create_absence
  resources :users
  resources :links
  resource :user, :only => :show, :as => :current_user

  resources :file_uploads, :except => [ :new, :show ] do
    collection do
      get ':page_id/new', :action => :new, :as => :new_with_page
    end
  end

  match "/downloads/:id" => "file_uploads#show", :as => :download_file

  match "/session/login" => "session#login", :via => :get
  match "/session/start" => "session#start", :via => :get
  match "/session/complete" => "session#complete", :via => :get
  match "/session/logout" => "session#logout", :via => :get

  match "/blog/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_news, :via => :get
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_news, :via => :delete
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_news, :via => :put
  resources :news, :controller => :pages do
    get 'rss', :on => :collection
  end

  resources :categories, :except => :show

  match "/page/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_page, :via => :get
  match "/page/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_page, :via => :delete
  match "/page/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_page, :via => :put
  resources :pages do
    member do
      get 'activate'
      get 'deactivate'
    end
    collection do
      get 'preview'
      get ':id/:comment_id/edit', :action => :edit_comment, :as => :edit_comment
      put ':id/:comment_id', :action => :update_comment, :as => :update_comment
      post ':id/create_comment', :action => :create_comment, :as => :create_comment
      post ':id/create_comment_preview', :action => :create_comment_preview, :as => :create_comment_preview
      delete ':id/:comment_id/destroy_comment', :action => :destroy_comment, :as => :destroy_comment
    end
  end

  match "/config" => "conf#index", :via => :get
  match "/config" => "conf#update", :via => :put
  match "/config/check_twitter" => "conf#check_twitter", :via => :get
  match "/config/check_google" => "conf#check_google", :via => :get
  match "/config/create_google_calendar" => "conf#create_google_calendar", :via => :post
  match "/config/pull_github" => "conf#pull_github", :via => :get

  match "/credits" => "pages#credits"
  match "/setup" => "pages#setup"

  if Rails.env.development?
    match "/backdoor" => "users#backdoor", :via => :get
  end

  root :to => "pages#home"

#   match "*a" => "application#http_404"
end

ups/app/views/shared/_backdoor.html.erb
<div class="actions" style="width: auto; position: absolute; top: 5px; right: 5px; background: #fff; padding: 5px; border: 1px solid #900; -moz-border-radius: 2px;">
  current: <span style="color: #000;"><%= user.role %></span>
  switch to:
  <%= link_to "admin", backdoor_path(:role => "admin"), :class => "user" %>
  <%= link_to "member", backdoor_path(:role => "member"), :class => "user" %>
  <%= link_to "user", backdoor_path(:role => "user"), :class => "user" %>
  <%= link_to "guest", backdoor_path(:role => "guest"), :class => "user" %>
</div>

ups/app/views/shared/_comment_form.html.erb
<fieldset>
  <% if signed_in? %>
    <div class="field">
      <label>name:</label>
      <%= user.name %>
    </div>
  <% else %>
    <div class="field">
      <label>
        name:
      </label>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <label>
        email:
      </label>
      <%= f.text_field :email %>
    </div>
  <% end %>
  <div class="field">
    <label>
      comment:
    </label>
    <%= f.text_area :text, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit "save", :class => "continue" %>
  </div>
</fieldset>

ups/app/views/shared/_comments.html.erb
<% if page.comments.any? %>
  <h2>comments:</h2>
  <% page.comments.each do |comment| %>
    <fieldset class="comment">
      <p>
        <%= comment.text %>
      </p>
      <p class="footer actions">
        author:
        <% if comment.user.present? %>
          <%= link_to comment.user.name, comment.user, :class => "user" %>
          <% if @current_user == comment.user || has_role?(:admin) %>
            <%= link_to "edit", edit_comment_pages_path(page.id, comment.id), :class => "edit" %>
            <%= link_to "del", destroy_comment_pages_path(page.id, comment.id), :confirm => "Are you sure?", :method => :delete, :class => "delete" %>
          <% end %>
        <% else %>
          <%= comment.name %> (<%= comment.email %>)
        <% end %>
      </p>
    </fieldset>
  <% end %>
<% end %>
<% if page.enable_comments %>
  <h2>add new comment:</h2>
  <%= form_for :comment, :url => create_comment_pages_path, :method => :post do |f| %>
    <%= render 'shared/comment_form', :f => f, :user => @current_user %>
  <% end %>
<% end %>

ups/app/views/shared/_download_links.html.erb
<% if (object.file_uploads.find_all { |f| f.visible }).any? %>
<div class="actions">
  <h4>
    attachments:
  </h4>
  <ul>
    <% (object.file_uploads.find_all { |f| f.visible }).each do |file_upload| %>
    <li>
      <%= link_to file_upload.filename, download_file_path(file_upload), :class => "download" %>, Downloads: <%= file_upload.count %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

ups/app/views/shared/_file_upload_index.html.erb
<fieldset>
  <% if file_uploads.present? %>
  <table>
    <thead>
      <tr>
        <th>
          Filename
        </th>
        <th>
          Size
        </th>
        <th>
          Page
        </th>
        <th>
          Downloads
        </th>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
      </tr>
    </thead>
    <tbody>
      <% file_uploads.each do |file_upload| %>
      <tr>
        <td>
          <%= link_to file_upload.filename, download_file_path(file_upload) %>
          <div class="kramdown_reference">
            <h5>
              kramdown reference:
            </h5>
            <code>
              [[[<%= file_upload.filename %>]]]
            </code>
            <br/>
            <code>
              ![[<%= file_upload.filename %>]]
            </code>
            as picture
            <br/>
            <code>
              [[[<%= file_upload.id %>]]]
            </code>
            <br/>
            <code>
              ![[<%= file_upload.id %>]]
            </code>
            as picture
          </div>
        </td>
        <td>
          <%= number_to_human_size(file_upload.file.size) %>
        </td>
        <td>
          <%= page_title file_upload.page if file_upload.page.present? %>
        </td>
        <td>
          <%= file_upload.count %>
        </td>
        <td class="actions">
          <%= link_to "download", download_file_path(file_upload), :class => "download" %>
        </td>
        <td class="actions">
          <%= link_to "edit", edit_file_upload_path(file_upload), :class => "edit" %>
        </td>
        <td class="actions">
          <%= link_to "delete", file_upload, :confirm => "Are you sure?", :method => :delete, :class => "delete", %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <% if edit_page.present? %>
    <p class="actions">
      <%= link_to "upload file", new_with_page_file_uploads_path(edit_page.id), :class => "new" %>
    </p>
  <% end %>
</fieldset>

ups/app/views/shared/_linklist.html.erb
<div class="list links">
  <%= linklist("Allgemein") %>
</div>

ups/app/views/shared/_sidebar.html.erb
<section class="sidebar right">
  <% if has_role_with_hierarchy?(:member) %>
    <p class="actions">
      <%= link_to "new post", new_news_path, :class => "new" %>
    </p>
  <% end %>
  <% if any_category? %>
  <section class="categories">
    <h3>categories:</h3>
    <%= list_categories %>
  </section>
  <% end %>
  <% if any_tag? %>
  <section class="tags">
    <h3>tags:</h3>
    <%= tag_cloud %>
  </section>
  <% end %>
</section>

ups/app/views/shared/_text_form.html.erb
<% f.fields_for :page_contents do |content_fields| %>
  <%= content_fields.hidden_field :language_id %>
  <div id="<%= "content_tab_"  + content_fields.object.language.short %>">
    <div class="field">
      <label>
        in language:
      </label>
      <%= content_fields.object.language.name %>
    </div>
    <div class="field">
      <label>
        title:
      </label>
      <%= content_fields.text_field :title %>
    </div>
    <% if edit_page.forced_url.nil? %>
      <div class="field">
        <label>
          excerpt:
        </label>
        <%= content_fields.text_area :excerpt, :rows => 3 %>
      </div>
      <div class="field">
        <label>
          text (kramdown):
        </label>
        <%= content_fields.text_area :text, :class => "kramdown", :short => content_fields.object.language.short %>
      </div>
      <div class="field">
        <label>
          preview:
        </label>
      </div>
      <div class="preview" id="preview_<%= content_fields.object.language.short %>"></div>
    <% end %>
  </div>
<% end %>

ups/app/views/shared/_twitter.html.erb
<div class="list twitter">
  <h2>twitter:</h2>
  <script src="http://widgets.twimg.com/j/2/widget.js"></script>
  <script>
  new TWTR.Widget({
    version: 2,
    type: 'profile',
    rpp: 4,
    interval: 6000,
    width: 250,
    height: 400,
    theme: {
      shell: {
        background: '#f0f0f0',
        color: '#aaaaaa'
      },
      tweets: {
        background: '#f0f0f0',
        color: '#000000',
        links: '#000099'
      }
    },
    features: {
      scrollbar: false,
      loop: false,
      live: false,
      hashtags: true,
      timestamp: true,
      avatars: false,
      behavior: 'all'
    }
  }).render().setUser('11awe23').start();
  </script>
</div>