ups/config/routes.rb
Ups::Application.routes.draw do
  resources :events do
    member do
      delete 'vote/:user_vote_id' => "events#user_vote_destroy", :as => :delete_user_votes
      put 'vote' => "events#vote", :as => :vote
      get 'timeslot/new' => "events#new_timeslot", :as => :new_timeslot
      delete 'timeslot/:timeslot_id' => "events#destroy_timeslot", :as => :destroy_timeslot
      get 'finish' => "events#finish", :as => :finish
      put 'reopen' => "events#reopen", :as => :reopen
      put 'finish' => "events#finished", :as => :finished
    end
  end

  match "/calendar" => "events#calendar", :via => :get
  match "/calendar/absence/new" => "events#new_absence", :via => :get, :as => :new_absence
  match "/calendar/absence" => "events#create_absence", :via => :post, :as => :create_absence
  resources :users
  resources :links
  resource :user, :only => :show, :as => :current_user

  resources :file_uploads, :except => [ :new, :show ] do
    collection do
      get ':page_id/new', :action => :new, :as => :new_with_page
    end
  end

  match "/downloads/:id" => "file_uploads#show", :as => :download_file

  match "/session/login" => "session#login", :via => :get
  match "/session/start" => "session#start", :via => :get
  match "/session/complete" => "session#complete", :via => :get
  match "/session/logout" => "session#logout", :via => :get

  match "/blog/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_news, :via => :get
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_news, :via => :delete
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_news, :via => :put
  resources :news, :controller => :pages do
    get 'rss', :on => :collection
  end

  resources :categories, :except => :show

  match "/page/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_page, :via => :get
  match "/page/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_page, :via => :delete
  match "/page/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_page, :via => :put
  resources :pages do
    member do
      get 'activate'
      get 'deactivate'
    end
    collection do
      get 'preview'
      get ':id/:comment_id/edit', :action => :edit_comment, :as => :edit_comment
      put ':id/:comment_id', :action => :update_comment, :as => :update_comment
      post ':id/create_comment', :action => :create_comment, :as => :create_comment
      post ':id/create_comment_preview', :action => :create_comment_preview, :as => :create_comment_preview
      delete ':id/:comment_id/destroy_comment', :action => :destroy_comment, :as => :destroy_comment
    end
  end

  match "/config" => "conf#index", :via => :get
  match "/config" => "conf#update", :via => :put
  match "/config/check_twitter" => "conf#check_twitter", :via => :get
  match "/config/check_google" => "conf#check_google", :via => :get
  match "/config/create_google_calendar" => "conf#create_google_calendar", :via => :post
  match "/config/pull_github" => "conf#pull_github", :via => :get

  match "/credits" => "pages#credits"
  match "/setup" => "pages#setup"

  if Rails.env.development?
    match "/backdoor" => "users#backdoor", :via => :get
  end

  root :to => "pages#home"

#   match "*a" => "application#http_404"
end

ups/app/models/event.rb
# == Schema Information
# Schema version: 20110302161658
#
# Table name: events
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  user_id     :integer
#  location    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  end_at      :datetime
#  description :text
#  finished    :boolean
#

class Event < ActiveRecord::Base
  attr_accessible :name, :user_id, :location, :end_at, :description, :finished, :timeslots_attributes, :user_votes_attributes

  belongs_to :user
  has_many :timeslots, :dependent => :destroy
  accepts_nested_attributes_for :timeslots, :allow_destroy => true

  has_many :user_votes, :dependent => :destroy
  accepts_nested_attributes_for :user_votes

  validates :name, :presence => true, :length => { :maximum => 255 }
  validates :location, :presence => true, :length => { :maximum => 255 }
  validates :user_id, :presence => true

  def votable?
    end_at.nil? || end_at? && end_at.future? && !finished?
  end

  def editable_for_user?(user, admin = false)
    !finished? && (self.user == user || admin)
  end
end

ups/app/controllers/events_controller.rb
require 'pp'
class EventsController < ApplicationController

  include GoogleHelper
  include ConfHelper

  before_filter :load_event, :except => [ :new, :create, :calendar, :index, :user_vote_destroy, :new_absence, :create_absence ]
  before_filter :load_user_vote, :only => :user_vote_destroy

  filter_access_to :edit, :update, :attribute_check => true
  filter_access_to :user_vote_destroy, :model => UserVote, :attribute_check => true
  filter_access_to :all

  def calendar
    @title = "Calendar"
  end

  def new_absence
    @title = "new absence"

    @timeslot = Timeslot.new(:user_id => @current_user.id)
  end

  def create_absence
    # convert string to int (month, ... )
    time = params[:time].each_with_object({}) { |(k,v),h| h[k] = v.to_i }

    start_at = DateTime.civil_from_format("local", time["start_at(1i)"], time["start_at(2i)"], time["start_at(3i)"], 0, 0)
    end_at = DateTime.civil_from_format("local", time["end_at(1i)"], time["end_at(2i)"], time["end_at(3i)"], 0, 0)

    gevent = {
      :title => "absence: #{@current_user.name}",
      :content => params[:description],
      :start_time => start_at.strftime("%Y-%m-%dT%H:%M:%S"),
      :end_time => end_at.strftime("%Y-%m-%dT%H:%M:%S"),
      :all_day => true
    }

    google = google_auth
    created_event_on_google = google_add_event(google, gevent)
    if created_event_on_google[:saved]
      flash[:success] = "absence created"
    else
      flash[:error] = "error"
    end

    redirect_to :action => :calendar
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event].merge(:user_id => @current_user.id))

    if @event.save
      flash[:success] = "vote created"
      redirect_to edit_event_path @event
    else
      flash.now[:error] = "vote not created"
      render 'new'
    end
  end

  def edit
    #loading in before_filter
  end

  def update
    if @event.update_attributes(params[:event])
      flash[:success] = "vote updated"
      redirect_to edit_event_path @event
    else
      flash.now[:error] = "vote update failed"
      render 'edit'
    end
  end

  def new_timeslot
    @event.timeslots.build(:start_at => DateTime.now, :end_at => DateTime.now.advance(:hours => 1)).save

    redirect_to edit_event_path @event
  end

  def finish
    #loading in before_filter
  end

  def finished
    if @event.update_attributes(params[:event])
      @timeslots=[]
      @event.timeslots.each do |timeslot|
        @timeslots << timeslot if timeslot.choosen?
      end

      @event.update_attribute :finished, true

      if google_check
        if @timeslots.empty?
          flash[:notice] = "no event created"
        else
          count=0
          google = google_auth
          @timeslots.each do |timeslot|
            gevent = {
              :title => @event.name,
              :content => @event.description,
              :where => @event.location,
              :start_time => timeslot.start_at.strftime("%Y-%m-%dT%H:%M:%S"),
              :end_time => timeslot.end_at.strftime("%Y-%m-%dT%H:%M:%S")
            }
            created_event_on_google = google_add_event(google, gevent)
            if created_event_on_google[:saved]
              timeslot.update_attribute :gevent_id, created_event_on_google[:event].id
              count += 1
            end
          end

          if count > 0
            flash[:success] = view_context.pluralize(count, "event") + " (of #{@timeslots.count}) created"
          else
            flash[:error] = "no events created"
          end
        end
        redirect_to calendar_path
      else
        flash[:notice] = "event finished"
        redirect_to events_path
      end
    else
      flash.now[:error] = "error"
      render 'finish'
    end
  end

  def reopen
    @event.finished = false

    google = google_auth
    @event.timeslots.each do |timeslot|
      if (timeslot.gevent_id? && gevent = google_find_event(google, timeslot.gevent_id))
        gevent.delete unless gevent.status == :canceled
      end
      timeslot.update_attribute :gevent_id, nil
    end

    if @event.save
      flash[:success] = "event reopened"
      redirect_to edit_event_path @event
    else
      flash[:error] = "cannot reopened event"
      redirect_to events_path
    end
  end

  def vote
    if @event.update_attributes params[:event]
      flash[:success] = "vote succesful"
      redirect_to @event
    else
      p @event.errors
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path
  end

  def user_vote_destroy
    @user_vote.destroy

    redirect_to @user_vote.event
  end

  def index
    @events = Event.all
  end

  def show
    @title = @event.name

    @user_vote = @event.user_votes.find_by_user_id @current_user.id
    if @user_vote.nil? && !@event.finished?
      @user_vote = @event.user_votes.build(:user_id => @current_user.id)
      @event.timeslots.each do |timeslot|
        @user_vote.votes.build(:timeslot_id => timeslot.id)
      end
    end

    @vote_button = !@event.finished? && @user_vote.new_record?
    @finish_button = @current_user == @event.user

    @button_div =  @vote_button || @finish_button
  end

  private
    def load_event
      @event = Event.find params[:id]
    end

    def load_user_vote
      @user_vote = UserVote.find params[:user_vote_id]
    end

end

ups/app/helpers/events_helper.rb
module EventsHelper
end

ups/app/views/events/_form.html.erb
<%= render 'errors/form', :object => event %>
<div class="field">
  <label>
    Name:
  </label>
  <%= f.text_field :name %>
</div>
<div class="field">
  <label>
    Location:
  </label>
  <%= f.text_field :location %>
</div>
<div class="field">
  <label>
    Ende:
  </label>
  <%= f.datetime_select :end_at, :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
</div>
<div class="field">
  <label>
    Description:
  </label>
  <%= f.text_area :description %>
</div>

ups/app/views/events/_result.html.erb
<tr>
  <td>
    result
  </td>
  <% event.timeslots.each do |timeslot| %>
    <td class="vote result">
      <%= timeslot.acks %>
    </td>
  <% end %>
</tr>

ups/app/views/events/_user_vote.html.erb
<% unless user_vote.new_record? %>
  <tr>
    <td class="actions">
      <%= user_vote.user.name %>
      <% if user_vote.user == @current_user && !@event.finished? %>
        <%= link_to "del", delete_user_votes_event_path(@event.id, user_vote.id), :confirm => "Are you sure?", :method => :delete, :class => "delete" %>
      <% end %>
    </td>
    <% @event.timeslots.each do |timeslot| %>
      <% vote = timeslot.vote_for_user_vote user_vote %>
      <% if vote.present? && vote.ack  %>
        <td class="vote yes">YES</td>
      <% else %>
        <td class="vote no">NO</td>
      <% end %>
    <% end %>
  </tr>
<% else %>
  <tr>
    <td>
      <%= @current_user.name %>
    </td>
    <%= f.fields_for :user_votes, user_vote do |user_vote_form| %>
      <%= user_vote_form.hidden_field :user_id %>
      <%= user_vote_form.fields_for :votes, do |vote_form| %>
        <td>
          <%= vote_form.hidden_field :timeslot_id %>
          <%= vote_form.check_box :ack %>
        </td>
      <% end %>
    <% end %>
  </tr>
<% end %>

ups/app/views/events/calendar.html.erb
<% if Conf.calendar.present? %>
  <p class="actions">
    <%= link_to "create new event", new_event_path, :class => "new" %> <%= link_to "create absence", new_absence_path, :class => "new" %>
  </p>
  <iframe src="<%= Conf.calendar %>&amp;height=1150&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;color=%23182C57" style="width: 100%; height: 1150px;" frameborder="0" scrolling="no"></iframe>
<% else %>
  <p class="flash notice">
    there is no calendar defined. please contact your admin.
  </p>
<% end %>

ups/app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

ups/app/views/events/edit.html.erb
<p class="actions">
  <%= link_to "back", events_path, :class => "back" %>
</p>

<%= form_for(@event) do |f| %>
  <fieldset>
    <%= render 'form', :f => f, :event => @event %>
    <%= f.fields_for :timeslots do |ft| %>
      <fieldset>
        <div class="field">
          <label>
            start:
          </label>
          <%= ft.datetime_select :start_at, :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
        </div>
        <div class="field">
          <label>
            end:
          </label>
          <%= ft.datetime_select :end_at, :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
        </div>
        <div class="field">
          <label>
            vote count:
          </label>
          <%= ft.object.acks %>
        </div>
        <div class="field">
          Delete: <%= ft.check_box :_destroy %>
        </div>
      </fieldset>
    <% end %>
    <div class="actions">
      <%= f.submit :class => "continue" %>
    </div>
  <p class="actions">
    <%= link_to "add timeslot", new_timeslot_event_path(@event.id), :class => "new" %>
  </p>
  <p class="actions">
    <%= link_to "finish", finish_event_path(@event.id), :class => "finish" %>
  </p>
  </fieldset>
<% end %>

ups/app/views/events/finish.html.erb
<p>
  started at <%= @event.created_at %>, vote until <%= @event.end_at %>
</p>
<% if @event.description.present? %>
  <p>
    <%= @event.description %>
  </p>
<% end %>
<%= form_for @event, :url => { :action => "finished" } do |f| %>
  <fieldset>
    <table>
      <thead>
        <tr>
          <th>
          </th>
          <% @event.timeslots.each do |timeslot| %>
            <th>
              <%= timeslot.start_at %> - <br /><%= timeslot.end_at %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @event.user_votes.each do |user_vote| %>
          <%= render 'user_vote', :user_vote => user_vote, :f => f %>
        <% end %>
        <%= render 'result', :event => @event %>
        <tr>
          <td>
            Event for:
          </td>
          <%= f.fields_for :timeslots do |ft| %>
            <td>
              <%= ft.check_box :choosen %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
    <div class="actions">
      <%= f.submit "finish", :class => "continue" %>
    </div>
  </fieldset>
<% end %>

ups/app/views/events/index.html.erb
<% if @events.any? %>
<table>
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        vote until
      </th>
      <th>
      </th>
      <th>
      </th>
      <th>
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <body>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= event.name %>
        </td>
        <td>
          <%= event.end_at %>
        </td>
        <td class="actions">
          <% if event.votable? %>
            <%= link_to "vote", event, :class => "vote" %>
          <% else %>
            <%= link_to "show", event, :class => "continue" %>
          <% end %>
        </td>
        <td class="actions">
          <% if event.editable_for_user? @current_user, has_role?(:admin) %>
            <%= link_to "edit", edit_event_path(event), :class => "edit" %>
          <% end %>
        </td>
        <td class="actions">
          <% if event.user == @current_user || has_role?(:admin) %>
            <% unless event.finished? %>
              <%= link_to "finish", finish_event_path(event), :class => "finish" %>
            <% else %>
              <%= link_to "reopen", reopen_event_path(event), :confirm => "Are you sure?", :method => :put, :class => "reopen" %>
            <% end %>
          <% end %>
        </td>
        <td class="actions">
          <% if event.user == @current_user || has_role?(:admin) %>
            <%= link_to "delete", event, :confirm => "Are you sure?", :method => :delete, :class => "delete" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </body>
</table>
<% end %>
<p class="actions">
  <%= link_to "create new event", new_event_path, :class => "new" %>
</p>

ups/app/views/events/new.html.erb
<p class="actions">
  <%= link_to "back", events_path, :class => "back" %>
</p>

<%= form_for(@event) do |f| %>
  <fieldset>
  <%= render 'form', :f => f, :event => @event%>
  <div class="actions">
      <%= f.submit :class => "new" %>
    </div>
  </fieldset>
<% end %>

ups/app/views/events/new_absence.html.erb
<%= form_tag create_absence_path, :method => :post do %>
  <fieldset>
    <div class="field">
      <label>
        start:
      </label>
      <%= date_select "time", "start_at", :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
    </div>
    <div class="field">
      <label>
        end:
      </label>
      <%= date_select "time", "end_at", :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
    </div>
    <div class="field">
      <label>
        description:
      </label>
      <%= text_area_tag :description, nil, :rows => 5 %>
    </div>
    <div class="actions">
      <%= submit_tag "create", :confirm => "Are you sure?", :class => "continue" %>
    </div>
  </fieldset>
<% end %>

ups/app/views/events/show.html.erb
<p>
  started at <%= @event.created_at %>, vote until <%= @event.end_at %>
</p>
<% if @event.description.present? %>
  <p>
    <%= @event.description %>
  </p>
<% end %>
<%= form_for @event, :url => { :action => "vote" } do |f| %>
  <fieldset>
    <table>
      <thead>
        <tr>
          <th>
            from:<br />
            to:
          </th>
          <% @event.timeslots.each do |timeslot| %>
            <th>
              <%= timeslot.start_at %><br />
              <%= timeslot.end_at %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @event.user_votes.each do |user_vote| %>
          <%= render 'user_vote', :user_vote => user_vote, :f => f %>
        <% end %>
      <%= render 'result', :event => @event %>
      </tbody>
    </table>
    <% if @button_div %>
      <div class="actions">
        <% if @vote_button %>
          <%= f.submit "vote", :class => "continue" %>
        <% end %>
        <% if @finish_button %>
          <% unless @event.finished? %>
            <%= link_to "finish", finish_event_path(@event), :class => "finish" %>
          <% else %>
            <%= link_to "reopen", reopen_event_path(@event), :confirm => "Are you sure?", :method => :put, :class => "reopen" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </fieldset>
<% end %>