ups/config/routes.rb
Ups::Application.routes.draw do
  resources :events do
    member do
      delete 'vote/:user_vote_id' => "events#user_vote_destroy", :as => :delete_user_votes
      put 'vote' => "events#vote", :as => :vote
      get 'timeslot/new' => "events#new_timeslot", :as => :new_timeslot
      delete 'timeslot/:timeslot_id' => "events#destroy_timeslot", :as => :destroy_timeslot
      get 'finish' => "events#finish", :as => :finish
      put 'reopen' => "events#reopen", :as => :reopen
      put 'finish' => "events#finished", :as => :finished
    end
  end

  match "/calendar" => "events#calendar", :via => :get
  match "/calendar/absence/new" => "events#new_absence", :via => :get, :as => :new_absence
  match "/calendar/absence" => "events#create_absence", :via => :post, :as => :create_absence
  resources :users
  resources :links
  resource :user, :only => :show, :as => :current_user

  resources :file_uploads, :except => [ :new, :show ] do
    collection do
      get ':page_id/new', :action => :new, :as => :new_with_page
    end
  end

  match "/downloads/:id" => "file_uploads#show", :as => :download_file

  match "/session/login" => "session#login", :via => :get
  match "/session/start" => "session#start", :via => :get
  match "/session/complete" => "session#complete", :via => :get
  match "/session/logout" => "session#logout", :via => :get

  match "/blog/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_news, :via => :get
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_news, :via => :delete
  match "/blog/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_news, :via => :put
  resources :news, :controller => :pages do
    get 'rss', :on => :collection
  end

  resources :categories, :except => :show

  match "/page/:id/(:int_title)(/:language_short)" => "pages#show", :as => :show_page, :via => :get
  match "/page/:id/(:int_title)(/:language_short)" => "pages#destroy", :as => :show_page, :via => :delete
  match "/page/:id/(:int_title)(/:language_short)" => "pages#update", :as => :show_page, :via => :put
  resources :pages do
    member do
      get 'activate'
      get 'deactivate'
    end
    collection do
      get 'preview'
      get ':id/:comment_id/edit', :action => :edit_comment, :as => :edit_comment
      put ':id/:comment_id', :action => :update_comment, :as => :update_comment
      post ':id/create_comment', :action => :create_comment, :as => :create_comment
      post ':id/create_comment_preview', :action => :create_comment_preview, :as => :create_comment_preview
      delete ':id/:comment_id/destroy_comment', :action => :destroy_comment, :as => :destroy_comment
    end
  end

  match "/config" => "conf#index", :via => :get
  match "/config" => "conf#update", :via => :put
  match "/config/check_twitter" => "conf#check_twitter", :via => :get
  match "/config/check_google" => "conf#check_google", :via => :get
  match "/config/create_google_calendar" => "conf#create_google_calendar", :via => :post
  match "/config/pull_github" => "conf#pull_github", :via => :get

  match "/credits" => "pages#credits"
  match "/setup" => "pages#setup"

  if Rails.env.development?
    match "/backdoor" => "users#backdoor", :via => :get
  end

  root :to => "pages#home"

#   match "*a" => "application#http_404"
end

ups/app/views/pages/_form.html.erb
<section class="sidebar right">
  <% if edit_page.page_type == :news %>
    <% if any_category? %>
      <section class="categories">
        <h3>
          categories:
        </h3>
        <ul>
          <% f.fields_for :page_categories do |cat_f| %>
          <li>
            <%= cat_f.check_box :checked %><%= category_name(cat_f.object.category) %>
            <%= cat_f.hidden_field :category_id %>
          </li>
          <% end %>
        </ul>
      </section>
    <% end %>
    <section class="tags">
      <h3>
        tags:
      </h3>
      <%= f.text_field :tags_string, :size => 23 %>
    </section>
  <% else %>
    <section class="categories">
      <h3>position:</h3>
      <%= possible_page_position_options(edit_page) %>
    </section>
  <% end %>
</section>
<fieldset>
  <%= render 'errors/form', :object => edit_page %>
  <% if edit_page.page_type == :page %>
    <div class="field actions">
      <label>
        title:
      </label>
      <span><%= page_title edit_page %>
        <i>(<%= (edit_page.int_title or "new") %>)</i></span>
      <span><%= link_to "activate", activate_page_path(edit_page), :class => "enable" if page_activateable? edit_page %>
      </span>
      <span><%= link_to "deactivate", deactivate_page_path(edit_page), :class => "disable" if page_deactivateable? edit_page %>
      </span>
    </div>
  <% end %>
  <div class="field">
    <label>
      visible after:
    </label>
    <%= f.datetime_select :start_at, :order => [:day, :month, :year], :date_seperator => ".", :time_seperator => ":" %>
  </div>
  <% if edit_page.page_type == :page %>
    <%= render 'role_edit', :f => f, :edit_page => edit_page %>
  <% end %>
  <div class="field">
    <label>
      allow comments:
    </label>
    <%= f.check_box :enable_comments %>
  </div>
  <fieldset id="content_tabs">
    <ul>
      <% edit_page.page_contents.each do |content| %>
      <li>
        <%= link_to content.language.name, "#content_tab_"+content.language.short %>
      </li>
      <% end %>
    </ul>
    <%= render 'shared/text_form', :f => f, :edit_page => edit_page %>
  </fieldset>
  <% if edit_page.id? && edit_page.forced_url.nil? %>
    <%= render 'shared/file_upload_index', :file_uploads => edit_page.file_uploads, :edit_page => edit_page %>
  <% end %>
  <div class="actions">
    <%= f.submit :class => "continue" %>
  </div>
</fieldset>
<script type="text/javascript">
  $(function(){
      $("#content_tabs").tabs();
  })

  function preview(id) {
    lang_short = $("#" + id).attr("short");
    value = escape($("#" + id).val());
    $.getScript("<%= preview_pages_path :js %>?&short=" + lang_short + "&text=" + value);
  }

  var preview_timeout = null;

  function schedule_preview(ev) {
    if(preview_timeout != null)
      window.clearTimeout(preview_timeout);
    preview_timeout = window.setTimeout("preview('" + this.id + "')", 1000);
  }

  $(function() {
    $(".kramdown").keyup(schedule_preview).each(function(i) {
      preview(this.id);
    });
  });
</script>

ups/app/views/pages/_index.html.erb
<tr>
  <td class="treecell"<%= make_treecell_style(depth) %>>
    <%= ((select_by_language_id(page.page_contents) and select_by_language_id(page.page_contents).title) or "(new)") %>
    <div class="kramdown_reference">
      <h5>
        kramdown reference:
      </h5>
      <code>
        [[<%= page.int_title %>]]
      </code>
      <br/>
      <code>
        [[<%= page.id %>]]
      </code>
    </div>
  </td>
  <td>
    <%= "deactivated" unless page.enabled? %>
    <%= "at " + page.start_at if page.enabled? unless page.visible? %>
  </td>
  <td class="actions">
    <% page.page_contents.sort_by { |page_content| page_content.language.name }.each do |page_content| %>
    <%= link_to page_content.language.name, edit_page_path(page.id), :class => "edit" %>
    <% end %>
  </td>
  <td class="actions">
    <%= link_to "show", make_page_path(page), :class => "continue" if page_visible? page %>
    <%= link_to "activate", activate_page_path(page), :class => "enable" if page_activateable? page %>
  </td>
  <td class="actions">
    <%= link_to "edit", edit_page_path(page), :class => "edit" if page_editable? page %>
  </td>
  <td class="actions">
    <%= link_to "delete", page, :confirm => "Are you sure?", :method => :delete, :class => "delete" if page_deleteable? page %>
    <%= link_to "deactivate", deactivate_page_path(page), :class => "disable" if page_deactivateable? page %>
  </td>
</tr>
<% editable_children_pages(page).each do |page| %>
  <%= render 'index', :page => page, :depth => depth + 1 %>
<% end %>

ups/app/views/pages/_role_edit.html.erb
<% if edit_page.forced_url.nil?  && edit_page != Conf.default_page %>
  <div class="field">
    <label>
      visible for:
    </label>
    <%= f.select :role_id, roles_options %>
  </div>
<% end %>
<% if page_edit_role_changeable? edit_page %>
  <div class="field">
    <label>
      editable for:
    </label>
    <%= f.select :edit_role_id, edit_roles_options %>
  </div>
<% end %>

ups/app/views/pages/credits.html.erb
<h1>credits</h1>
<p>
  this software has been created at awe11, agile webentwicklung at university of bremen.
</p>
<p>
  by allspark and <a href="http://notrademark.de/">msquare</a>, concepts by dmke
</p>
<p>
  <strong>Icons:</strong>
  <a href="http://famfamfam.com/lab/icons/silk/">Silk Icon Set</a>
  (<a href="http://creativecommons.org/licenses/by/2.5/">CC-by 2.5</a>
  <a href="http://famfamfam.com">famfamfam.com</a>)
</p>
<p><a href="http://validator.w3.org/check?uri=" style="color: #090;">valid html5</a></p>

ups/app/views/pages/edit.html.erb
<p class="actions">
  <%= link_to "back", show_path(@edit_page), :class => "back" %>
  <%= link_to "index", index_path, :class => "back" %>
</p>
<%= form_for @edit_page, :url => show_path(@edit_page), :html => { :method => :put } do |f| %>
  <%= render 'form', :f => f, :edit_page => @edit_page %>
<% end %>

ups/app/views/pages/edit_comment.html.erb
<%= form_for @comment, :url => update_comment_pages_path  do |f| %>
  <%= render 'shared/comment_form', :f => f, :user => @current_user %>
<% end %>

ups/app/views/pages/index.html.erb
<% if @pages.any? %>
  <table>
    <thead>
      <tr>
        <th>
          title
        </th>
        <th>
          visible
        </th>
        <th>
          languages
        </th>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <%= render 'index', :page => page, :depth => 0 %>
      <% end %>
    </tbody>
  </table>
<% end %>
<p class="actions">
  <%= link_to "new page", new_page_path, :class => "new" %>
</p>

ups/app/views/pages/index_news.html.erb
<%= render 'shared/sidebar' %>
<% if @browse_category.present? %>
  <h2>Category: <%= category_name @browse_category %></h2>
<% end %>
<% if @browse_tags.present? %>
  <h2>Browse tags: <%= @browse_tags_names.join ", " %></h2>
<% end %>
<% @pages.each do |news| %>
  <section class="news">
    <h2><%= link_to page_title(news), news_path(news) %></h2>
    <p>
      <%= page_excerpt(news) %>
    </p>
    <p class="footer actions">
      <% if news.user.present? %>
        <span>author: <%= link_to news.user.name, news.user, :class => "user" %></span>
      <% else %>
        <span><i>(author deleted)</i></span>
      <% end %>
      <span>from: <%= news.updated_at %></span>
      <% if news.categories.any? %>
        <span>categories: <%= inline_categories_for news %></span>
      <% end %>
      <% if news.tags.any? %>
        <span>tags: <%= inline_tags_for news %></span>
      <% end %>
    </p>
  </section>
<% end %>
<% if @pages.empty? %>
  <p class="flash notice news">no post matched your search criterias.</p>
<% end %>

ups/app/views/pages/new.html.erb
<p class="actions">
  <%= link_to "back", index_path, :class => "back" %>
</p>
<%= form_for @edit_page, :url => index_path, :html => { :method => :post } do |f| %>
  <%= render 'form', :f => f, :edit_page => @edit_page %>
<% end %>

ups/app/views/pages/preview.js.erb
$("<%= @field %>").html("<%= escape_javascript(raw(@html)) %>");

ups/app/views/pages/setup.html.erb
<h1>you need to do some setup</h1>

<ul>
	<li>use <code>rake db:seed</code> to fill in default system data</li>
</ul>

ups/app/views/pages/show.html.erb
<%= page_text(@page) %>
<p class="footer actions">
  <% if @page.user.present? %>
    <span>
      author: <%= link_to @page.user.name, @page.user, :class => "user" %>
    </span>
  <% else %>
    <span>
      <i>
        (author deleted)
      </i>
    </span>
  <% end %>
    <span>
      from: <%= @page.updated_at %>
    </span>
  <% if @page.categories.any? %>
    <span>
      categories: <%= inline_categories_for(@page) %>
    </span>
  <% end %>
</p>
<%= render 'shared/download_links', :object => @page %>

<% if visible_children_pages(@page).any? %>
  <h2>subpages:</h2>
  <ul>
    <% visible_children_pages(@page).each do |news| %>
      <li><%= link_to page_title(news), make_page_path(news) %><%= " - " + page_excerpt(news) if page_excerpt(news).present? %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'shared/comments', :page => @page %>

ups/app/views/pages/show_news.html.erb
<%= render 'shared/sidebar' %>
<section class="news">
  <% if page_editable? @page %>
  <p class="actions">
    <%= link_to "edit", edit_news_path(@page), :class => "edit" %>
    <%= link_to "delete", news_path(@page), :confirm => "Are you sure?", :method => :delete, :class => "delete" %>,
    kramdown reference:
    <code>
      [[<%= @page.int_title %>]]
    </code>
    or
    <code>
      [[<%= @page.id %>]]
    </code>
  </p>
  <% end %>
  <fieldset>
    <%= page_text(@page) %>
  </fieldset>
  <p class="footer actions">
    <% if @page.user.present? %>
    <span>
      author: <%= link_to @page.user.name, @page.user, :class => "user" %>
    </span>
    <% else %>
    <span>
      <i>
        (author deleted)
      </i>
    </span>
    <% end %>
    <span>
      from: <%= @page.updated_at %>
    </span>
    <% if @page.categories.any? %>
    <span>
      categories: <%= inline_categories_for(@page) %>
    </span>
    <% end %>
  </p>
</section>
<%= render 'shared/download_links', :object => @page %>

<%= render 'shared/comments', :page => @page %>